# Generated by Django 4.1.1 on 2022-10-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Krosovks',
            new_name='Krosovka',
        ),
    ]
